=== latchset/crypto-auditing/docs/query.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/latchset/crypto-auditing/docs/query.schema.json",
  "title": "crypto-auditing query output format",
  "description": "Output format of crau-query command",
  "$defs": {
    "Span": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "context": { "type": "string" },
          "origin": { "type": "string" },
          "command": { "type": "string" },
          "start": { "type": "number" },
          "end": { "type": "number" },
          "events": {
            "type": "object",
            "properties": {
              "name": { "type": "string" }
            },
            "patternProperties": {
              "^[^:]+::.+$": {
                "type": ["string", "number"]
              }
            },
            "additionalProperties": true,
            "requires": ["name"]
          },
          "spans": { "$ref": "#/$defs/Span" }
        }
      }
    }
  },
  "$ref": "#/$defs/Span"
}

=== latchset/crypto-auditing/fixtures/logs/since-until/since-until.json
[
  {
    "context": "ccb9432c9c2c8c203230e6b7d31c0b16",
    "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
    "command": "",
    "start": 1771974863.214706,
    "end": 1771974863.214706,
    "events": {
      "name": "tls::handshake_client",
      "tls::protocol_version": 772
    },
    "spans": [
      {
        "context": "4496299804038c7e426b63ba21e82767",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2148774,
        "end": 1771974863.2148774,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 23
        },
        "spans": [
          {
            "context": "f4a8575856bd5e71c9cfeb08004b18a8",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2148807,
            "end": 1771974863.2148807,
            "events": {
              "name": "pk::generate",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1"
            }
          }
        ]
      },
      {
        "context": "5d965925626f231276ab4658c070f0bb",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2293024,
        "end": 1771974863.2293024,
        "events": {
          "name": "tls::verify",
          "tls::signature_algorithm": 1027
        },
        "spans": [
          {
            "context": "5ffa226b4b1b2e03ac33f016c368daf5",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.22932,
            "end": 1771974863.22932,
            "events": {
              "name": "pk::verify",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1",
              "pk::hash": "SHA256"
            }
          }
        ]
      },
      {
        "context": "9c3eb879769d1ca094404184669f6d60",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2288046,
        "end": 1771974863.2288046,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 4588
        },
        "spans": [
          {
            "context": "464cbb78dccd784c9b70a5592a97c067",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.229047,
            "end": 1771974863.229047,
            "events": {
              "name": "pk::derive",
              "pk::algorithm": "ECDH (X25519)"
            }
          },
          {
            "context": "6b12b88a73508c86569afb171fc86fa2",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2288072,
            "end": 1771974863.2288072,
            "events": {
              "name": "pk::decapsulate",
              "pk::algorithm": "ML-KEM-768"
            }
          }
        ]
      },
      {
        "context": "f574d1bf35c80d999cd45243992cbcf3",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2472508,
        "end": 1771974863.2472508,
        "events": {
          "name": "pk::verify",
          "pk::algorithm": "RSA",
          "pk::bits": 2048
        }
      }
    ]
  }
]

=== latchset/crypto-auditing/fixtures/logs/since-until/since.json
[
  {
    "context": "ccb9432c9c2c8c203230e6b7d31c0b16",
    "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
    "command": "",
    "start": 1771974863.214706,
    "end": 1771974863.214706,
    "events": {
      "name": "tls::handshake_client",
      "tls::protocol_version": 772
    },
    "spans": [
      {
        "context": "4496299804038c7e426b63ba21e82767",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2148774,
        "end": 1771974863.2148774,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 23
        },
        "spans": [
          {
            "context": "f4a8575856bd5e71c9cfeb08004b18a8",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2148807,
            "end": 1771974863.2148807,
            "events": {
              "name": "pk::generate",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1"
            }
          }
        ]
      },
      {
        "context": "5d965925626f231276ab4658c070f0bb",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2293024,
        "end": 1771974863.2293024,
        "events": {
          "name": "tls::verify",
          "tls::signature_algorithm": 1027
        },
        "spans": [
          {
            "context": "5ffa226b4b1b2e03ac33f016c368daf5",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.22932,
            "end": 1771974863.22932,
            "events": {
              "name": "pk::verify",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1",
              "pk::hash": "SHA256"
            }
          }
        ]
      },
      {
        "context": "9c3eb879769d1ca094404184669f6d60",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2288046,
        "end": 1771974863.2288046,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 4588
        },
        "spans": [
          {
            "context": "464cbb78dccd784c9b70a5592a97c067",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.229047,
            "end": 1771974863.229047,
            "events": {
              "name": "pk::derive",
              "pk::algorithm": "ECDH (X25519)"
            }
          },
          {
            "context": "6b12b88a73508c86569afb171fc86fa2",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2288072,
            "end": 1771974863.2288072,
            "events": {
              "name": "pk::decapsulate",
              "pk::algorithm": "ML-KEM-768"
            }
          }
        ]
      },
      {
        "context": "f574d1bf35c80d999cd45243992cbcf3",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2472508,
        "end": 1771974863.2472508,
        "events": {
          "name": "pk::verify",
          "pk::algorithm": "RSA",
          "pk::bits": 2048
        }
      }
    ]
  },
  {
    "context": "ba622d5b9877a430162242de965c3a3e",
    "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
    "command": "",
    "start": 1771974923.4500113,
    "end": 1771974923.4500113,
    "events": {
      "name": "tls::handshake_client",
      "tls::protocol_version": 772
    },
    "spans": [
      {
        "context": "086f6407cbc7d1ab26012b7e939373c4",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974923.4649017,
        "end": 1771974923.4649017,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 4588
        },
        "spans": [
          {
            "context": "849055c3278578d687c4b54c828ec440",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974923.4649038,
            "end": 1771974923.4649038,
            "events": {
              "name": "pk::decapsulate",
              "pk::algorithm": "ML-KEM-768"
            }
          },
          {
            "context": "dbdb8d7e3703cb023b12c41af91cad51",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974923.465125,
            "end": 1771974923.465125,
            "events": {
              "name": "pk::derive",
              "pk::algorithm": "ECDH (X25519)"
            }
          }
        ]
      },
      {
        "context": "174de05063ba9b25008b373abab6edc2",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974923.4501987,
        "end": 1771974923.4501987,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 23
        },
        "spans": [
          {
            "context": "ac972e44ea6bcef3b4a63cbe53a80cc9",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974923.4502006,
            "end": 1771974923.4502006,
            "events": {
              "name": "pk::generate",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1"
            }
          }
        ]
      },
      {
        "context": "520f84448e7d46817efd218659951f35",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974923.4855325,
        "end": 1771974923.4855325,
        "events": {
          "name": "pk::verify",
          "pk::algorithm": "RSA",
          "pk::bits": 2048
        }
      },
      {
        "context": "7efbca0e91133d460bbabf918ea3d2d5",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974923.4654472,
        "end": 1771974923.4654472,
        "events": {
          "name": "tls::verify",
          "tls::signature_algorithm": 1027
        },
        "spans": [
          {
            "context": "631afe9e5424d5b5b2a69e94388704d7",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974923.465482,
            "end": 1771974923.465482,
            "events": {
              "name": "pk::verify",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1",
              "pk::hash": "SHA256"
            }
          }
        ]
      }
    ]
  }
]

=== latchset/crypto-auditing/fixtures/logs/since-until/until.json
[
  {
    "context": "77c5eac18916f65560e4a72c378fa571",
    "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
    "command": "",
    "start": 1771974803.010886,
    "end": 1771974803.010886,
    "events": {
      "name": "tls::handshake_client",
      "tls::protocol_version": 772
    },
    "spans": [
      {
        "context": "3cb4522554c9b0dc609cb15a60e8066d",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974803.0110753,
        "end": 1771974803.0110753,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 23
        },
        "spans": [
          {
            "context": "a585d1425ae9a1bb716ef919a7077b79",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974803.0110772,
            "end": 1771974803.0110772,
            "events": {
              "name": "pk::generate",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1"
            }
          }
        ]
      },
      {
        "context": "8bea2cd10c263427b8ea8f7a75ab63dc",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974803.0253136,
        "end": 1771974803.0253136,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 4588
        },
        "spans": [
          {
            "context": "56cef1e26f5035c51e0df469ac338f5d",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974803.025316,
            "end": 1771974803.025316,
            "events": {
              "name": "pk::decapsulate",
              "pk::algorithm": "ML-KEM-768"
            }
          },
          {
            "context": "bd1bf0fb3d99d6695865fa2bbef92b34",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974803.0255075,
            "end": 1771974803.0255075,
            "events": {
              "name": "pk::derive",
              "pk::algorithm": "ECDH (X25519)"
            }
          }
        ]
      },
      {
        "context": "ba2f7865e4de038b3da670176ac134aa",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974803.0425448,
        "end": 1771974803.0425448,
        "events": {
          "name": "pk::verify",
          "pk::algorithm": "RSA",
          "pk::bits": 2048
        }
      },
      {
        "context": "dcb5668c7981c908da00c4f485aa28fe",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974803.0257778,
        "end": 1771974803.0257778,
        "events": {
          "name": "tls::verify",
          "tls::signature_algorithm": 1027
        },
        "spans": [
          {
            "context": "0c7af68a3db1a3f26781b44c3b74f372",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974803.025795,
            "end": 1771974803.025795,
            "events": {
              "name": "pk::verify",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1",
              "pk::hash": "SHA256"
            }
          }
        ]
      }
    ]
  },
  {
    "context": "ccb9432c9c2c8c203230e6b7d31c0b16",
    "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
    "command": "",
    "start": 1771974863.214706,
    "end": 1771974863.214706,
    "events": {
      "name": "tls::handshake_client",
      "tls::protocol_version": 772
    },
    "spans": [
      {
        "context": "4496299804038c7e426b63ba21e82767",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2148774,
        "end": 1771974863.2148774,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 23
        },
        "spans": [
          {
            "context": "f4a8575856bd5e71c9cfeb08004b18a8",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2148807,
            "end": 1771974863.2148807,
            "events": {
              "name": "pk::generate",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1"
            }
          }
        ]
      },
      {
        "context": "5d965925626f231276ab4658c070f0bb",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2293024,
        "end": 1771974863.2293024,
        "events": {
          "name": "tls::verify",
          "tls::signature_algorithm": 1027
        },
        "spans": [
          {
            "context": "5ffa226b4b1b2e03ac33f016c368daf5",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.22932,
            "end": 1771974863.22932,
            "events": {
              "name": "pk::verify",
              "pk::algorithm": "EC/ECDSA",
              "pk::curve": "SECP256R1",
              "pk::hash": "SHA256"
            }
          }
        ]
      },
      {
        "context": "9c3eb879769d1ca094404184669f6d60",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2288046,
        "end": 1771974863.2288046,
        "events": {
          "name": "tls::key_exchange",
          "tls::group": 4588
        },
        "spans": [
          {
            "context": "464cbb78dccd784c9b70a5592a97c067",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.229047,
            "end": 1771974863.229047,
            "events": {
              "name": "pk::derive",
              "pk::algorithm": "ECDH (X25519)"
            }
          },
          {
            "context": "6b12b88a73508c86569afb171fc86fa2",
            "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
            "command": "",
            "start": 1771974863.2288072,
            "end": 1771974863.2288072,
            "events": {
              "name": "pk::decapsulate",
              "pk::algorithm": "ML-KEM-768"
            }
          }
        ]
      },
      {
        "context": "f574d1bf35c80d999cd45243992cbcf3",
        "origin": "25afdfb85a5c7626b28a77ac4dce92637f7c842a",
        "command": "",
        "start": 1771974863.2472508,
        "end": 1771974863.2472508,
        "events": {
          "name": "pk::verify",
          "pk::algorithm": "RSA",
          "pk::bits": 2048
        }
      }
    ]
  }
]
